// Code generated by protoc-gen-go. DO NOT EDIT.
// source: upspin.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:

	upspin.proto

It has these top-level messages:

	Endpoint
	Location
	Refdata
	EndpointRequest
	EndpointResponse
	StoreGetRequest
	StoreGetResponse
	StorePutRequest
	StorePutResponse
	StoreDeleteRequest
	StoreDeleteResponse
	User
	KeyLookupRequest
	KeyLookupResponse
	KeyPutRequest
	KeyPutResponse
	EntryError
	EntriesError
	DirLookupRequest
	DirPutRequest
	DirGlobRequest
	DirDeleteRequest
	DirWhichAccessRequest
	DirWatchRequest
	Event
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Endpoint mirrors upspin.Endpoint.
type Endpoint struct {
	Transport int32  `protobuf:"varint,1,opt,name=transport" json:"transport,omitempty"`
	NetAddr   string `protobuf:"bytes,2,opt,name=net_addr,json=netAddr" json:"net_addr,omitempty"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto1.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Endpoint) GetTransport() int32 {
	if m != nil {
		return m.Transport
	}
	return 0
}

func (m *Endpoint) GetNetAddr() string {
	if m != nil {
		return m.NetAddr
	}
	return ""
}

// Location mirrors upspin.Location.
type Location struct {
	Endpoint  *Endpoint `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	Reference string    `protobuf:"bytes,2,opt,name=reference" json:"reference,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto1.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Location) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

func (m *Location) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

// Refdata mirrors upspin.Refdata.
type Refdata struct {
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
	Volatile  bool   `protobuf:"varint,2,opt,name=volatile" json:"volatile,omitempty"`
	Duration  int64  `protobuf:"varint,3,opt,name=duration" json:"duration,omitempty"`
}

func (m *Refdata) Reset()                    { *m = Refdata{} }
func (m *Refdata) String() string            { return proto1.CompactTextString(m) }
func (*Refdata) ProtoMessage()               {}
func (*Refdata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Refdata) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *Refdata) GetVolatile() bool {
	if m != nil {
		return m.Volatile
	}
	return false
}

func (m *Refdata) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type EndpointRequest struct {
}

func (m *EndpointRequest) Reset()                    { *m = EndpointRequest{} }
func (m *EndpointRequest) String() string            { return proto1.CompactTextString(m) }
func (*EndpointRequest) ProtoMessage()               {}
func (*EndpointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type EndpointResponse struct {
	Endpoint *Endpoint `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
}

func (m *EndpointResponse) Reset()                    { *m = EndpointResponse{} }
func (m *EndpointResponse) String() string            { return proto1.CompactTextString(m) }
func (*EndpointResponse) ProtoMessage()               {}
func (*EndpointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EndpointResponse) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type StoreGetRequest struct {
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
}

func (m *StoreGetRequest) Reset()                    { *m = StoreGetRequest{} }
func (m *StoreGetRequest) String() string            { return proto1.CompactTextString(m) }
func (*StoreGetRequest) ProtoMessage()               {}
func (*StoreGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StoreGetRequest) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

type StoreGetResponse struct {
	Data      []byte      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Refdata   *Refdata    `protobuf:"bytes,2,opt,name=refdata" json:"refdata,omitempty"`
	Locations []*Location `protobuf:"bytes,3,rep,name=locations" json:"locations,omitempty"`
	Error     []byte      `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *StoreGetResponse) Reset()                    { *m = StoreGetResponse{} }
func (m *StoreGetResponse) String() string            { return proto1.CompactTextString(m) }
func (*StoreGetResponse) ProtoMessage()               {}
func (*StoreGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StoreGetResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StoreGetResponse) GetRefdata() *Refdata {
	if m != nil {
		return m.Refdata
	}
	return nil
}

func (m *StoreGetResponse) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *StoreGetResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type StorePutRequest struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *StorePutRequest) Reset()                    { *m = StorePutRequest{} }
func (m *StorePutRequest) String() string            { return proto1.CompactTextString(m) }
func (*StorePutRequest) ProtoMessage()               {}
func (*StorePutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StorePutRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type StorePutResponse struct {
	Refdata *Refdata `protobuf:"bytes,1,opt,name=refdata" json:"refdata,omitempty"`
	Error   []byte   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *StorePutResponse) Reset()                    { *m = StorePutResponse{} }
func (m *StorePutResponse) String() string            { return proto1.CompactTextString(m) }
func (*StorePutResponse) ProtoMessage()               {}
func (*StorePutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *StorePutResponse) GetRefdata() *Refdata {
	if m != nil {
		return m.Refdata
	}
	return nil
}

func (m *StorePutResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type StoreDeleteRequest struct {
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
}

func (m *StoreDeleteRequest) Reset()                    { *m = StoreDeleteRequest{} }
func (m *StoreDeleteRequest) String() string            { return proto1.CompactTextString(m) }
func (*StoreDeleteRequest) ProtoMessage()               {}
func (*StoreDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *StoreDeleteRequest) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

type StoreDeleteResponse struct {
	Error []byte `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *StoreDeleteResponse) Reset()                    { *m = StoreDeleteResponse{} }
func (m *StoreDeleteResponse) String() string            { return proto1.CompactTextString(m) }
func (*StoreDeleteResponse) ProtoMessage()               {}
func (*StoreDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StoreDeleteResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type User struct {
	Name        string      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Dirs        []*Endpoint `protobuf:"bytes,2,rep,name=dirs" json:"dirs,omitempty"`
	Stores      []*Endpoint `protobuf:"bytes,3,rep,name=stores" json:"stores,omitempty"`
	PublicKey   string      `protobuf:"bytes,4,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	Attestation []byte      `protobuf:"bytes,5,opt,name=attestation,proto3" json:"attestation,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto1.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDirs() []*Endpoint {
	if m != nil {
		return m.Dirs
	}
	return nil
}

func (m *User) GetStores() []*Endpoint {
	if m != nil {
		return m.Stores
	}
	return nil
}

func (m *User) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *User) GetAttestation() []byte {
	if m != nil {
		return m.Attestation
	}
	return nil
}

type KeyLookupRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
}

func (m *KeyLookupRequest) Reset()                    { *m = KeyLookupRequest{} }
func (m *KeyLookupRequest) String() string            { return proto1.CompactTextString(m) }
func (*KeyLookupRequest) ProtoMessage()               {}
func (*KeyLookupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *KeyLookupRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type KeyLookupResponse struct {
	User  *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Error []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *KeyLookupResponse) Reset()                    { *m = KeyLookupResponse{} }
func (m *KeyLookupResponse) String() string            { return proto1.CompactTextString(m) }
func (*KeyLookupResponse) ProtoMessage()               {}
func (*KeyLookupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *KeyLookupResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *KeyLookupResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type KeyPutRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *KeyPutRequest) Reset()                    { *m = KeyPutRequest{} }
func (m *KeyPutRequest) String() string            { return proto1.CompactTextString(m) }
func (*KeyPutRequest) ProtoMessage()               {}
func (*KeyPutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *KeyPutRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type KeyPutResponse struct {
	Error []byte `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *KeyPutResponse) Reset()                    { *m = KeyPutResponse{} }
func (m *KeyPutResponse) String() string            { return proto1.CompactTextString(m) }
func (*KeyPutResponse) ProtoMessage()               {}
func (*KeyPutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *KeyPutResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type EntryError struct {
	Entry []byte `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Error []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *EntryError) Reset()                    { *m = EntryError{} }
func (m *EntryError) String() string            { return proto1.CompactTextString(m) }
func (*EntryError) ProtoMessage()               {}
func (*EntryError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *EntryError) GetEntry() []byte {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *EntryError) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type EntriesError struct {
	Entries [][]byte `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Error   []byte   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *EntriesError) Reset()                    { *m = EntriesError{} }
func (m *EntriesError) String() string            { return proto1.CompactTextString(m) }
func (*EntriesError) ProtoMessage()               {}
func (*EntriesError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *EntriesError) GetEntries() [][]byte {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *EntriesError) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type DirLookupRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DirLookupRequest) Reset()                    { *m = DirLookupRequest{} }
func (m *DirLookupRequest) String() string            { return proto1.CompactTextString(m) }
func (*DirLookupRequest) ProtoMessage()               {}
func (*DirLookupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *DirLookupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DirPutRequest struct {
	Entry []byte `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (m *DirPutRequest) Reset()                    { *m = DirPutRequest{} }
func (m *DirPutRequest) String() string            { return proto1.CompactTextString(m) }
func (*DirPutRequest) ProtoMessage()               {}
func (*DirPutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *DirPutRequest) GetEntry() []byte {
	if m != nil {
		return m.Entry
	}
	return nil
}

type DirGlobRequest struct {
	Pattern string `protobuf:"bytes,1,opt,name=pattern" json:"pattern,omitempty"`
}

func (m *DirGlobRequest) Reset()                    { *m = DirGlobRequest{} }
func (m *DirGlobRequest) String() string            { return proto1.CompactTextString(m) }
func (*DirGlobRequest) ProtoMessage()               {}
func (*DirGlobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *DirGlobRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type DirDeleteRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DirDeleteRequest) Reset()                    { *m = DirDeleteRequest{} }
func (m *DirDeleteRequest) String() string            { return proto1.CompactTextString(m) }
func (*DirDeleteRequest) ProtoMessage()               {}
func (*DirDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *DirDeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DirWhichAccessRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DirWhichAccessRequest) Reset()                    { *m = DirWhichAccessRequest{} }
func (m *DirWhichAccessRequest) String() string            { return proto1.CompactTextString(m) }
func (*DirWhichAccessRequest) ProtoMessage()               {}
func (*DirWhichAccessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *DirWhichAccessRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DirWatchRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Sequence int64  `protobuf:"varint,2,opt,name=sequence" json:"sequence,omitempty"`
}

func (m *DirWatchRequest) Reset()                    { *m = DirWatchRequest{} }
func (m *DirWatchRequest) String() string            { return proto1.CompactTextString(m) }
func (*DirWatchRequest) ProtoMessage()               {}
func (*DirWatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *DirWatchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirWatchRequest) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

// The first response in the stream is whether dir.Watch succeeded. If it
// didn't, the error field contains the error and no streaming happens. If it
// did succeed the error is nil and subsequent streams are from the Events
// channel.
type Event struct {
	Entry    []byte `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Sequence int64  `protobuf:"varint,2,opt,name=sequence" json:"sequence,omitempty"`
	Delete   bool   `protobuf:"varint,3,opt,name=delete" json:"delete,omitempty"`
	Error    []byte `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto1.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *Event) GetEntry() []byte {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *Event) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Event) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

func (m *Event) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto1.RegisterType((*Endpoint)(nil), "proto.Endpoint")
	proto1.RegisterType((*Location)(nil), "proto.Location")
	proto1.RegisterType((*Refdata)(nil), "proto.Refdata")
	proto1.RegisterType((*EndpointRequest)(nil), "proto.EndpointRequest")
	proto1.RegisterType((*EndpointResponse)(nil), "proto.EndpointResponse")
	proto1.RegisterType((*StoreGetRequest)(nil), "proto.StoreGetRequest")
	proto1.RegisterType((*StoreGetResponse)(nil), "proto.StoreGetResponse")
	proto1.RegisterType((*StorePutRequest)(nil), "proto.StorePutRequest")
	proto1.RegisterType((*StorePutResponse)(nil), "proto.StorePutResponse")
	proto1.RegisterType((*StoreDeleteRequest)(nil), "proto.StoreDeleteRequest")
	proto1.RegisterType((*StoreDeleteResponse)(nil), "proto.StoreDeleteResponse")
	proto1.RegisterType((*User)(nil), "proto.User")
	proto1.RegisterType((*KeyLookupRequest)(nil), "proto.KeyLookupRequest")
	proto1.RegisterType((*KeyLookupResponse)(nil), "proto.KeyLookupResponse")
	proto1.RegisterType((*KeyPutRequest)(nil), "proto.KeyPutRequest")
	proto1.RegisterType((*KeyPutResponse)(nil), "proto.KeyPutResponse")
	proto1.RegisterType((*EntryError)(nil), "proto.EntryError")
	proto1.RegisterType((*EntriesError)(nil), "proto.EntriesError")
	proto1.RegisterType((*DirLookupRequest)(nil), "proto.DirLookupRequest")
	proto1.RegisterType((*DirPutRequest)(nil), "proto.DirPutRequest")
	proto1.RegisterType((*DirGlobRequest)(nil), "proto.DirGlobRequest")
	proto1.RegisterType((*DirDeleteRequest)(nil), "proto.DirDeleteRequest")
	proto1.RegisterType((*DirWhichAccessRequest)(nil), "proto.DirWhichAccessRequest")
	proto1.RegisterType((*DirWatchRequest)(nil), "proto.DirWatchRequest")
	proto1.RegisterType((*Event)(nil), "proto.Event")
}

func init() { proto1.RegisterFile("upspin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 850 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xef, 0x6e, 0xe3, 0x44,
	0x10, 0x8f, 0xeb, 0xfc, 0x71, 0x26, 0xb9, 0x26, 0xdd, 0xbb, 0xf6, 0x7c, 0xe6, 0x10, 0xd1, 0xa2,
	0x3b, 0x22, 0x2a, 0xee, 0x4a, 0x38, 0xa1, 0x7e, 0x29, 0x10, 0x91, 0xa8, 0x12, 0xad, 0x50, 0x65,
	0x54, 0xf1, 0x31, 0x72, 0xe3, 0x2d, 0xb5, 0x9a, 0xda, 0x66, 0xbd, 0xae, 0x94, 0xc7, 0xe0, 0x03,
	0x0f, 0xc1, 0x23, 0xf0, 0x70, 0x48, 0x68, 0xd7, 0xbb, 0xf6, 0xda, 0x71, 0x02, 0xa7, 0x7e, 0x8a,
	0x67, 0xf6, 0xf7, 0x9b, 0xf9, 0xcd, 0xcc, 0xce, 0x06, 0xfa, 0x69, 0x9c, 0xc4, 0x41, 0xf8, 0x2e,
	0xa6, 0x11, 0x8b, 0x50, 0x4b, 0xfc, 0xe0, 0x1f, 0xc1, 0x9a, 0x87, 0x7e, 0x1c, 0x05, 0x21, 0x43,
	0xaf, 0xa1, 0xcb, 0xa8, 0x17, 0x26, 0x71, 0x44, 0x99, 0x6d, 0x8c, 0x8c, 0x71, 0xcb, 0x2d, 0x1c,
	0xe8, 0x15, 0x58, 0x21, 0x61, 0x0b, 0xcf, 0xf7, 0xa9, 0xbd, 0x37, 0x32, 0xc6, 0x5d, 0xb7, 0x13,
	0x12, 0x36, 0xf5, 0x7d, 0x8a, 0xaf, 0xc1, 0xba, 0x8c, 0x96, 0x1e, 0x0b, 0xa2, 0x10, 0x1d, 0x83,
	0x45, 0x64, 0x40, 0x11, 0xa3, 0x37, 0x19, 0x64, 0x19, 0xdf, 0xa9, 0x3c, 0xae, 0x45, 0xb4, 0x8c,
	0x94, 0xdc, 0x12, 0x4a, 0xc2, 0x25, 0x91, 0x41, 0x0b, 0x07, 0x5e, 0x40, 0xc7, 0x25, 0xb7, 0xbe,
	0xc7, 0xbc, 0x32, 0xd0, 0xa8, 0x00, 0x91, 0x03, 0xd6, 0x63, 0xb4, 0xf2, 0x58, 0xb0, 0xca, 0xa2,
	0x58, 0x6e, 0x6e, 0xf3, 0x33, 0x3f, 0xa5, 0x42, 0x9b, 0x6d, 0x8e, 0x8c, 0xb1, 0xe9, 0xe6, 0x36,
	0x3e, 0x80, 0x41, 0x2e, 0x8a, 0xfc, 0x9e, 0x92, 0x84, 0xe1, 0xef, 0x61, 0x58, 0xb8, 0x92, 0x38,
	0x0a, 0x13, 0xf2, 0x51, 0x25, 0xe1, 0xf7, 0x30, 0xf8, 0x85, 0x45, 0x94, 0x9c, 0x13, 0x15, 0x73,
	0xb7, 0x78, 0xfc, 0xa7, 0x01, 0xc3, 0x82, 0x21, 0x53, 0x22, 0x68, 0xf2, 0xba, 0x05, 0xba, 0xef,
	0x8a, 0x6f, 0x34, 0x86, 0x0e, 0xcd, 0xda, 0x21, 0x8a, 0xec, 0x4d, 0xf6, 0xa5, 0x0a, 0xd9, 0x24,
	0x57, 0x1d, 0xa3, 0xaf, 0xa0, 0xbb, 0x92, 0xf3, 0x48, 0x6c, 0x73, 0x64, 0x6a, 0x8a, 0xd5, 0x9c,
	0xdc, 0x02, 0x81, 0x5e, 0x40, 0x8b, 0x50, 0x1a, 0x51, 0xbb, 0x29, 0xb2, 0x65, 0x06, 0x7e, 0x23,
	0x0b, 0xb9, 0x4a, 0xf3, 0x42, 0x6a, 0x54, 0x61, 0x17, 0x86, 0x05, 0x4c, 0xaa, 0xd7, 0x94, 0x1a,
	0xbb, 0x95, 0xe6, 0xa9, 0xf7, 0xf4, 0xd4, 0x13, 0x40, 0x22, 0xe6, 0x8c, 0xac, 0x08, 0x23, 0xff,
	0xaf, 0x8d, 0xc7, 0xf0, 0xbc, 0xc4, 0x91, 0x52, 0xf2, 0x04, 0x86, 0x9e, 0xe0, 0x2f, 0x03, 0x9a,
	0xd7, 0x09, 0xa1, 0xbc, 0xa2, 0xd0, 0x7b, 0x50, 0xe1, 0xc4, 0x37, 0xfa, 0x1c, 0x9a, 0x7e, 0x40,
	0x13, 0x7b, 0x6f, 0x64, 0xd6, 0x8d, 0x5a, 0x1c, 0xa2, 0x2f, 0xa0, 0x9d, 0xf0, 0x74, 0xd5, 0xfe,
	0xe6, 0x30, 0x79, 0x8c, 0x3e, 0x05, 0x88, 0xd3, 0x9b, 0x55, 0xb0, 0x5c, 0xdc, 0x93, 0xb5, 0xe8,
	0x70, 0xd7, 0xed, 0x66, 0x9e, 0x0b, 0xb2, 0x46, 0x23, 0xe8, 0x79, 0x8c, 0x91, 0x84, 0x65, 0x37,
	0xb4, 0x25, 0x54, 0xea, 0x2e, 0xfc, 0x1e, 0x86, 0x17, 0x64, 0x7d, 0x19, 0x45, 0xf7, 0x69, 0xac,
	0x5a, 0xf1, 0x09, 0x74, 0xd3, 0x84, 0xd0, 0x85, 0xa6, 0xdd, 0xe2, 0x8e, 0x9f, 0xbd, 0x07, 0x82,
	0x7f, 0x82, 0x03, 0x8d, 0x20, 0xfb, 0xf0, 0x19, 0x34, 0x39, 0x40, 0xce, 0xa3, 0x27, 0xd5, 0xf2,
	0x1e, 0xb8, 0xe2, 0x60, 0xcb, 0x24, 0x4e, 0xe0, 0xd9, 0x05, 0x59, 0x6b, 0x57, 0xe0, 0xbf, 0xe2,
	0xe0, 0xb7, 0xb0, 0xaf, 0x18, 0x3b, 0x47, 0x70, 0x0a, 0x30, 0x0f, 0x19, 0x5d, 0xcf, 0xb9, 0x25,
	0x30, 0xdc, 0xca, 0x31, 0xdc, 0xd8, 0xa2, 0xe9, 0x3b, 0xe8, 0x73, 0x66, 0x40, 0x92, 0x8c, 0x6b,
	0x43, 0x87, 0x64, 0xb6, 0x6d, 0x8c, 0xcc, 0x71, 0xdf, 0x55, 0xe6, 0x16, 0xfe, 0x5b, 0x18, 0xce,
	0x02, 0x5a, 0x6e, 0x68, 0xcd, 0x3d, 0xc0, 0x6f, 0xe0, 0xd9, 0x2c, 0xa0, 0x5a, 0xed, 0xb5, 0x22,
	0xf1, 0x97, 0xb0, 0x3f, 0x0b, 0xe8, 0xf9, 0x2a, 0xba, 0x51, 0x38, 0x1b, 0x3a, 0x31, 0x9f, 0x20,
	0x0d, 0x65, 0x3c, 0x65, 0xca, 0xd4, 0xe5, 0x6b, 0x5d, 0x97, 0xfa, 0x18, 0x0e, 0x67, 0x01, 0xfd,
	0xf5, 0x2e, 0x58, 0xde, 0x4d, 0x97, 0x4b, 0x92, 0x24, 0xbb, 0xc0, 0x53, 0x18, 0x70, 0xb0, 0xc7,
	0x96, 0x77, 0x3b, 0x60, 0xfc, 0x21, 0x4c, 0xf8, 0xb1, 0x7a, 0x6a, 0x4d, 0x37, 0xb7, 0xf1, 0x6f,
	0xd0, 0x9a, 0x3f, 0x92, 0x70, 0x4b, 0x89, 0xbb, 0xa8, 0xe8, 0x08, 0xda, 0xbe, 0xa8, 0x47, 0xbc,
	0xae, 0x96, 0x2b, 0xad, 0xfa, 0x47, 0x65, 0xf2, 0x8f, 0x01, 0x2d, 0xb1, 0xa6, 0xe8, 0x4c, 0xfb,
	0xe3, 0x39, 0xaa, 0x2e, 0x4f, 0x56, 0x86, 0xf3, 0x72, 0xc3, 0x9f, 0x5d, 0x29, 0xdc, 0x40, 0xa7,
	0x60, 0x9e, 0x93, 0x82, 0x59, 0x79, 0x72, 0x9d, 0x97, 0x1b, 0x7e, 0x9d, 0x79, 0x95, 0x56, 0x98,
	0x57, 0x69, 0x3d, 0x53, 0xbb, 0xc6, 0xb8, 0x81, 0xa6, 0xd0, 0xce, 0x46, 0x87, 0x5e, 0xe9, 0xa0,
	0xd2, 0x38, 0x1d, 0xa7, 0xee, 0x48, 0x85, 0x98, 0xfc, 0x6d, 0x80, 0xc9, 0xd7, 0xfe, 0x89, 0xd5,
	0x9f, 0x41, 0x3b, 0xbb, 0xbf, 0x48, 0x81, 0xaa, 0x4f, 0x84, 0x63, 0x6f, 0x1e, 0xe4, 0xf4, 0x0f,
	0x59, 0x0b, 0x5e, 0x14, 0x10, 0xad, 0x01, 0x87, 0x15, 0x6f, 0xae, 0xfd, 0x0f, 0x13, 0xcc, 0x59,
	0x40, 0x9f, 0xaa, 0xfd, 0xdb, 0x0d, 0xed, 0xd5, 0x6d, 0x74, 0x0e, 0x72, 0xb6, 0x7a, 0x20, 0x70,
	0x03, 0x9d, 0x94, 0x45, 0x97, 0x56, 0xb3, 0x9e, 0xf1, 0x01, 0x9a, 0x7c, 0x2d, 0xd1, 0x61, 0x41,
	0xd1, 0xd6, 0xd4, 0x79, 0xae, 0x71, 0xd4, 0x63, 0x92, 0xe9, 0x93, 0x53, 0xd6, 0xf4, 0x95, 0x67,
	0x5c, 0x9b, 0xed, 0x07, 0xe8, 0x69, 0x0b, 0x8b, 0x5e, 0x17, 0xe4, 0xcd, 0x3d, 0xae, 0x8f, 0xf0,
	0x35, 0xb4, 0xc4, 0x16, 0xa3, 0x23, 0x8d, 0xab, 0xad, 0xb5, 0xd3, 0x57, 0x2c, 0xbe, 0xab, 0xb8,
	0x71, 0x62, 0xdc, 0xb4, 0x85, 0xe3, 0x9b, 0x7f, 0x07, 0x00, 0xc7, 0xd8, 0xf8, 0xe3, 0xdc, 0x09,
	0x00, 0x00,
}
